collections:
  artwork:
    output: true
  artwork-collection:
    output: true
    permalink: /artwork/collection/:name/

destination:
  ../dist

permalink: pretty

enviroment: dev

defaults:
  - scope:
      path: ""
      type: "artwork"
    values:
      missing-images: false
      layout: "artwork"
